### ISSUE TITLE
injective-protobuf isn't generating the types for all of the proto files

### ISSUE THREAD

**Issue by 0xForerunner** [InjectiveLabs/cw-injective#149]
Perhaps there is a reason for this that I'm not aware of, but it seems injective-protobuf is not building all of the types defined in the `.proto` files. An example being `EthAccount`. This can be fixed by simply adding the paths to the missing proto files into the inputs in `build.rs`. I would be happy to submit a PR for this if it will be accepted.

**Comment by 0xForerunner** [comment]
Additionally, it would be very helpful to have an official release on crates.io, even if it's just a beta release.

**Comment by maurolacy** [comment]
Please check if there are more types that need to be added.

It would also be a good opportunity to improve the release process of this package, and to define the authoritative sources of the third party packages, as they are not copied in `injective-core` anymore.

@albertchon, can you define the references for them? What about publishing this package to crates-io?

**Comment by maurolacy** [comment]
Some progress in #164.

Will publish to crates.io soon.
