### ISSUE TITLE
Create better conversions for FPDecimal and cosmwasm-std math types

### ISSUE THREAD

**Issue by 0xForerunner** [InjectiveLabs/cw-injective#155]
An example would be `From<Decimal256> for FPDecimal`
```rust
pub fn into_fp_decimal(value: Decimal256) -> FPDecimal {
    let atomics = value.atomics().to_be_bytes();
    FPDecimal { num: atomics.into(), sign: 1 }
}
```
but there are many more. As well some conversions seem to be using implementations for `Display` which likely isn't best practice.

**Comment by stackman27** [comment]
hi @ewoolsey, can i take on this issue? it seems pretty independent from the rest of issues

also you mentioned there are "many more better conversions" that we can do, could you please give me few more examples?

**Comment by 0xForerunner** [comment]
Just off the top of my head:

`TryFrom<FPDecimal> for Decimal256`

`From<Uint256> for FPDecimal`

`TryFrom<FPDecimal> for Uint256`

`into_uint256_ceil(self) -> Uint256`

`into_uint256_floor(self) -> Uint256`

I'm sure they would appreciate a PR.
