### ISSUE TITLE
[Registry] Add index for is_executable contracts 

### ISSUE THREAD

**Issue by albertchon** [InjectiveLabs/cw-injective#75]
Currently if there exist deactivated (not executable) contracts in the CONTRACTS map, `query_active_contracts` can return fewer contracts than the `limit` in the paginated query. 

https://github.com/InjectiveLabs/cw-injective/blob/7aa376fe4f58e59f09b3823931711d51a654313d/contracts/registry/src/contract.rs#L258-L265

We can use an IndexedMap to iterate solely over the executable contracts to resolve this issue. 
- [Notion doc ](https://www.notion.so/injective/Understanding-cw-storage-plus-State-eb98dad2a5ed4ddcb4dcf2e8a77135db#9d7db8f2ed704a12bfcd8936ef195a26)

**Comment by maurolacy** [comment]
Why don't just put `take(limit)` after `filter()`?

**Comment by albertchon** [comment]
Though this can work, it’s suboptimal in the case where there’s several deactivated contracts, which we then need to needlessly iterate through

**Comment by maurolacy** [comment]
Ah, I see. I'll create an `IndexedMap` then.
