### ISSUE TITLE
Injective math: decimal type

### ISSUE THREAD

**Issue by tk-o** [InjectiveLabs/cw-injective#82]
I noticed you've been maintaining your own decimal type. A while ago, I worked on [a basic SignedDecimal type for CosmWasm]( (https://github.com/atomiklabs/atl-cw/blob/master/packages/signed-decimal/src/signed_decimal.rs). It is based on `cosmwasm_std::Decimal` type.

Perhaps you'd like to use this type which is interoperable with the underlying type from CosmWasm STD.

I was wondering what are your thoughts about it? Thank you in advance for taking a look 🙃

**Comment by gorgos** [comment]
Thanks for the suggestion. We actually used https://github.com/nebula-protocol/nebula-contracts/tree/main/libraries/cluster-math/src/fp_decimal as initial reference, but added several features/fixes to it over time.

CosmWasm has an open issue about this here https://github.com/CosmWasm/cosmwasm/issues/1186 in case you want to share. They have signed decimals planned, maybe you'd like to share your code there. And once signed decimals are supported by CosmWasm itself, it definitely makes sense for us to switch.
